config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "genres#index"

  resources :games

  resources :genres

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :genre
	
	validates :name, presence: true, length: {maximum: 32}
	validates :genre_id, presence: true
	validates :discription, length: {maximum: 200}
	validates :release, :numericality => {:greater_than_or_equal => 1900, :less_than_or_equal => 2100}

	mount_uploader :image, ImageUploader
end

app/models/genre.rb
class Genre < ActiveRecord::Base
	has_many :games

	validates :name, presence: true, length: {maximum: 32}
	validates :description, length: {maximum: 200}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!, :except => [:index, :show]
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]
  
  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:name, :genre_id, :discription, :release, :image)
    end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_action :set_genre, only: [:show, :edit, :update, :destroy]

  # GET /genres
  # GET /genres.json
  def index
    @genres = Genre.all
  end

  # GET /genres/1
  # GET /genres/1.json
  def show
  end

  # GET /genres/new
  def new
    @genre = Genre.new
  end

  # GET /genres/1/edit
  def edit
  end

  # POST /genres
  # POST /genres.json
  def create
    @genre = Genre.new(genre_params)

    respond_to do |format|
      if @genre.save
        format.html { redirect_to @genre, notice: 'Genre was successfully created.' }
        format.json { render :show, status: :created, location: @genre }
      else
        format.html { render :new }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /genres/1
  # PATCH/PUT /genres/1.json
  def update
    respond_to do |format|
      if @genre.update(genre_params)
        format.html { redirect_to @genre, notice: 'Genre was successfully updated.' }
        format.json { render :show, status: :ok, location: @genre }
      else
        format.html { render :edit }
        format.json { render json: @genre.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /genres/1
  # DELETE /genres/1.json
  def destroy
    @genre.destroy
    respond_to do |format|
      format.html { redirect_to genres_url, notice: 'Genre was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_genre
      @genre = Genre.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def genre_params
      params.require(:genre).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br>
    <%= f.collection_select :genre_id, Genre.all, :id, :name, {:prompt => true} %>
  </div>
  <div class="field">
    <%= f.label :discription %><br>
    <%= f.text_area :discription, size: "60x12" %>
  </div>
  <div class="field">
    <%= f.label :release %><br>
    <%= f.number_field :release %>
  </div>
  <div class="field">
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game, :class => "button"%> 
<%= link_to 'Back', games_path, :class => "button" %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Genre</th>
      <th>Discription</th>
      <th>Release</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.name %></td>
        <td><%= game.genre.name %></td>
        <td><%= game.discription %></td>
        <td><%= game.release %></td>
        <td><%= image_tag game.image_url %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Show', game, :class => "button tiny" %></td>
          <td><%= link_to 'Edit', edit_game_path(game), :class => "button tiny" %></td>
          <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button tiny" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Game', new_game_path, :class => "button" %>
<% end %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path, :class => "button" %>

app/views/games/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Name:</strong>
  <%= @game.name %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @game.genre.name %>
</p>

<p>
  <strong>Discription:</strong>
  <%= @game.discription %>
</p>

<p>
  <strong>Release:</strong>
  <%= @game.release %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @game.image_url %>
</p>
<% if user_signed_in? %>
	<%= link_to 'Edit', edit_game_path(@game), :class => "button" %> 
	<%= link_to 'Back', games_path, :class => "button" %>
<% end %>

app/views/genres/_form.html.erb
<%= form_for(@genre) do |f| %>
  <% if @genre.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@genre.errors.count, "error") %> prohibited this genre from being saved:</h2>

      <ul>
      <% @genre.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, size: "60x12" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/genres/edit.html.erb
<h1>Editing genre</h1>

<%= render 'form' %>

<%= link_to 'Show', @genre, :class => "button" %> 
<%= link_to 'Back', genres_path, :class => "button" %>

app/views/genres/index.html.erb
<h1>Listing genres</h1>


    <% @genres.each do |genre| %>
        <h2><%= link_to genre.name, genre %></h2>
          <ul>
            <% genre.games.each do |game| %>
            <h3>
              <%= image_tag game.image_url %>
              <%= link_to game.name, game %>
            </h3>
            <% end %>
          </ul>
    <% end %>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Genre', new_genre_path, :class => "button" %>
<% end %>

app/views/genres/new.html.erb
<h1>New genre</h1>

<%= render 'form' %>

<%= link_to 'Back', genres_path, :class => "button" %>

app/views/genres/show.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<p>
  <strong>Name:</strong>
  <%= @genre.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @genre.description %>
</p>
<% if user_signed_in? %>
<%= link_to 'Edit', edit_genre_path(@genre), :class => "button" %> 
<td><%= link_to 'Destroy', @genre, method: :delete, data: { confirm: 'Are you sure?' }, :class => "button" %></td>
<%= link_to 'Back', genres_path, :class => "button" %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">GameDB</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <ul class="right">
      <% if user_signed_in? %>
        <li><a>Logged in as <strong><%= current_user.email %></strong>.</a></li>
        <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path , method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign up", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>

    <!-- Left Nav Section -->
    <ul class="left">
      <li><%= link_to 'Genres', root_path, :class => "Button" %></li>
      <li><%= link_to 'Games', "/games" %></li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% if notice %>
    <div data-alert class="alert-box alert radius"><%=notice %></div>
    <% end %>
    <% if alert %>
    	<div data-alert class="alert-box warning radius"><%= alert %></div>
    <% end %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>